# Generated by Django 5.0.1 on 2024-01-06 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('branch', models.CharField(choices=[('CIV', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('INF', 'Information Technology'), ('CSM', 'Computer Science - Artificial Intelligence and Machine Learning'), ('CSO', 'Computer Science - Internet of Things'), ('CIC', 'Computer Science - Internet of Things & Cybersecurity'), ('AIM', 'Artificial Intelligence and Machine Learning'), ('AID', 'Artificial Intelligence and Data Science')], max_length=3)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
