# Generated by Django 5.0.1 on 2024-01-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
    ]
